<?php

namespace Database\Seeders;

use App\Models\Faq;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FaqSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $url = config('app.url');
        $json_data = <<<JSON
        [
            {
                "question_en": "Trends in Waste Management",
                "question_km": "និន្នាការនៃការគ្រប់គ្រងសំណល់",
                "answer_en": "<p><span>Highlights of other solid waste management activities in Cambodia.</span></p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><figure class=\"image image_resized\" style=\"width:81.28%;\"><img src=\"$url/storage/ckeditor-images/photo_2020-09-13_11-06-50.jpg\"></figure><p style=\"text-align:center;\"><span><strong>Composting by COMPED</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:89.98%;\"><img src=\"$url/storage/ckeditor-images/Junlen - Copy.jpg\"></figure><p style=\"text-align:center;\"><span><strong>Vemicomposting by Junlen</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:75.08%;\"><img src=\"$url/storage/ckeditor-images/103525016_2643142335926187_9010259653798344801_n.jpg\"></figure><p style=\"text-align:center;\"><span><strong>Bio-briquette charcoal by Khmer</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:75.02%;\"><img src=\"$url/storage/ckeditor-images/87045299_107646024162669_809525709511852032_n.jpg\"></figure><p style=\"text-align:center;\"><span><strong>Waste Recycling by Black Soldier</strong></span></p></td></tr></tbody></table></figure>",
                "answer_km": "<p><span>ខាងក្រោមនេះជាការគូសបញ្ជាក់នៃសកម្មភាពគ្រប់គ្រងសំណល់ខ្លះៗក្នុងប្រទេសកម្ពុជា។</span></p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><figure class=\"image image_resized\" style=\"width:81.28%;\"><img src=\"$url/storage/ckeditor-images/photo_2020-09-13_11-06-50.jpg\"></figure><p style=\"text-align:center;\"><span><strong>ការកែច្នៃជីកំប៉ុសដោយអង្គការ​ COMPED</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:89.98%;\"><img src=\"$url/storage/ckeditor-images/Junlen - Copy.jpg\"></figure><p style=\"text-align:center;\"><span><strong>ការកែច្នៃជីកំប៉ុសជន្លេនដោយ ​JUNLEN</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:75.08%;\"><img src=\"$url/storage/ckeditor-images/103525016_2643142335926187_9010259653798344801_n.jpg\"></figure><p style=\"text-align:center;\"><span><strong>ការកែច្នៃ ធ្យូងអនាម័យ​ដោយ សហគ្រាស​ Khmer Green Charcoal</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:75.02%;\"><img src=\"$url/storage/ckeditor-images/87045299_107646024162669_809525709511852032_n.jpg\"></figure><p style=\"text-align:center;\"><span><strong>ការកែច្នៃសំណល់សរីរាង្គដោយ</strong></span><br><span><strong>Black Soldier Fly Cambodia</strong></span></p></td></tr></tbody></table></figure>",
                "sector_id": 1
            },
            {
                "question_en": "Other Types of Waste: Industrial Waste",
                "question_km": "សំណល់ប្រភេទផ្សេងៗ៖ សំណល់រឹងឧស្សាហកម្ម",
                "answer_en": "<p>Industrial Solid Waste is referred to hazardous solid waste generated from the production chains of the factories, enterprises and companies and shall be treated differently from municipal solid waste by professionals.</p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><figure class=\"image image_resized\" style=\"width:92.22%;\"><img src=\"$url/storage/ckeditor-images/industrial_before.JPG\"></figure><p style=\"text-align:center;\">Industrial Waste for Energy Recycling (before)</p></td><td><figure class=\"image image_resized\" style=\"width:91.8%;\"><img src=\"$url/storage/ckeditor-images/industrial_shredded.JPG\"></figure><p style=\"text-align:center;\"><span>Industrial Waste after shredding</span></p></td></tr></tbody></table></figure>",
                "answer_km": "<p>សំណល់រឹងឧស្សាហកម្ម សំដៅដល់សំណល់រឹងដែលមានគ្រោះថ្នាក់ដែលបានបន្សល់ ឬបង្កើតពីចង្វាក់ផលិតកម្ម នៃរោងចក្រ សហគ្រាស និងក្រុមហ៊ុន និងអាចត្រូវបានធ្វើប្រព្រឹត្តិកម្មតាមវិធីផ្សេងខុសពីប្រព្រឹត្តិកម្ម សំណល់រឹងទីប្រជុំជនដោយអ្នកជំនាញ។</p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><figure class=\"image image_resized\" style=\"width:92.22%;\"><img src=\"$url/storage/ckeditor-images/industrial_before.JPG\"></figure><p style=\"text-align:center;\">សំណល់រឹងឧស្សាហកម្មសម្រាប់ការកែច្នៃជាថាមពល (មុនពេលកាត់ជាបំណែក)</p></td><td><figure class=\"image image_resized\" style=\"width:91.8%;\"><img src=\"$url/storage/ckeditor-images/industrial_shredded.JPG\"></figure><p style=\"text-align:center;\"><span>សំណល់រឹងឧស្សាហកម្ម ក្រោយពេលកាត់ជាបំណែក</span></p></td></tr></tbody></table></figure>",
                "sector_id": 1
            },
            {
                "question_en": "What to Do with Electronics",
                "question_km": "អ្វីដែលគួរធ្វើសម្រាប់គ្រឿងបរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក",
                "answer_en": "<ul><li>Properly store e-waste separate from other residential waste.</li><li>Discharge or transfer e-waste to the e-waste treatment facilities or collection points as assigned by competent authorities. For example:<ul><li>Electronic repair shops</li><li>E-waste Treatment facilities</li><li>E-waste Junk shops<br>&nbsp;</li></ul></li></ul>",
                "answer_km": "<ul><li>រក្សាទុកសំណល់បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក​ដាច់​ដោយ​ឡែក​ពីសំណល់តាមផ្ទះប្រភេទផ្សេង។</li><li>បញ្ចេញ ឬ បញ្ជូនសំណល់បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក ទៅកន្លែងធ្វើប្រព្រឹត្តិកម្មសំណល់បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក ឬទីតាំងប្រមូលដែលមានជំនាញច្បាស់លាស់។ ឧទាហរណ៍៖&nbsp;<ul><li>ហាងជួសជុលបរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក&nbsp;</li><li>កន្លែងធ្វើប្រព្រឹត្តិកម្មសំណល់បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក</li><li>ដេប៉ូអេតចាយ ដែលទទួលទិញសំណល់បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក<br>&nbsp;</li></ul></li></ul>",
                "sector_id": 1
            },
            {
                "question_en": "Other Types of Waste: Hazardous Waste",
                "question_km": "សំណល់ប្រភេទផ្សេងៗ៖ សំណល់គ្រោះថ្នាក់",
                "answer_en": "<p>Hazardous waste refers to radioactivity substances, explosive substances, toxic substances, inflammable substances, pathogenic substances, irritating substances, corrosive substances, oxidizing substances, or other chemical substances which may cause the dange.</p><p>Citizens should pay more attention to these wastes and store them separately from residential wastes until they can be disposed of properly.&nbsp;<br>&nbsp;</p><figure class=\"table\" style=\"width:96.46%;\"><table><colgroup><col style=\"width:49.82%;\"><col style=\"width:50.18%;\"></colgroup><tbody><tr><td><p style=\"text-align:center;\"><span><strong>E-waste</strong></span></p><figure class=\"image image_resized\" style=\"width:75.81%;\"><img src=\"$url/storage/ckeditor-images/kisspng-global-it-distribution-sdn-bhd-computer-hardware-c-5b33e8952c1f58.9354926415301285331807.png\"></figure></td><td><p style=\"text-align:center;\"><span><strong>Chemical Waste</strong></span></p><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/kisspng-household-hazardous-waste-plastic-household-hazardous-waste-5b1daec7a971d5.3264693715286719436941.png\"></figure></td></tr><tr><td><p style=\"text-align:center;\"><span><strong>Construction Waste</strong></span></p><figure class=\"image image_resized\" style=\"width:88.28%;\"><img src=\"$url/storage/ckeditor-images/kisspng-construction-waste-architectural-engineering-waste-waste-management-5ac0f6c1c49ea8.0789317315225955218054 (1).png\"></figure></td><td><p style=\"text-align:center;\"><span><strong>Medical Waste</strong></span></p><figure class=\"image image_resized\" style=\"width:78.29%;\"><img src=\"$url/storage/ckeditor-images/kisspng-medicine-nursing-drawing-doodle-medical-supplies-artwork-5aa1121385a852.2469974315205053635475.png\"></figure></td></tr><tr><td><p style=\"text-align:center;\"><span><strong>Rubber/leather Waste</strong></span></p><figure class=\"image image_resized\" style=\"width:82.23%;\"><img src=\"$url/storage/ckeditor-images/pngegg (13).png\"></figure></td><td>&nbsp;</td></tr></tbody></table></figure>",
                "answer_km": "<p>សំណល់គ្រោះថ្នាក់សំដៅទៅសំណល់​មានផ្ទុកសារធាតុវិទ្យុសកម្ម សារធាតុផ្ទុះ ពុល ឆេះ ចំលងជំងឺ សារធាតុ​ធ្វើឱ្យ​រលាក ធ្វើឱ្យច្រេះ ធ្វើអុកស៊ីតកម្ម ឫសារធាតុគីមីផ្សេងៗ ដែលអាចបង្កឱ្យមានគ្រោះថ្នាក់។</p><p>ប្រជាពលរដ្ឋគួរធ្វើការយកចិត្តទុកដាក់​បន្ថែមទៀតលើប្រភេទ​សំណល់ទាំងនេះ និង​រក្សា​វាទុកដាច់ដោយឡែកពីសំណល់តាមផ្ទះប្រភេទផ្សេង រហូត​ដល់សំណល់ទាំងនេះអាចយកទៅចោលបានដោយត្រឹមត្រូវ។<br>&nbsp;</p><figure class=\"table\" style=\"width:96.46%;\"><table><colgroup><col style=\"width:49.82%;\"><col style=\"width:50.18%;\"></colgroup><tbody><tr><td><p style=\"text-align:center;\"><span><strong>សំណល់បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិក</strong></span></p><figure class=\"image image_resized\" style=\"width:75.81%;\"><img src=\"$url/storage/ckeditor-images/kisspng-global-it-distribution-sdn-bhd-computer-hardware-c-5b33e8952c1f58.9354926415301285331807.png\"></figure></td><td><p style=\"text-align:center;\"><span><strong>សំណល់មានផ្ទុកសារធាតុ​គីមី</strong></span></p><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/kisspng-household-hazardous-waste-plastic-household-hazardous-waste-5b1daec7a971d5.3264693715286719436941.png\"></figure></td></tr><tr><td><p style=\"text-align:center;\"><span><strong>សំណល់សំណង់</strong></span></p><figure class=\"image image_resized\" style=\"width:88.28%;\"><img src=\"$url/storage/ckeditor-images/kisspng-construction-waste-architectural-engineering-waste-waste-management-5ac0f6c1c49ea8.0789317315225955218054 (1).png\"></figure></td><td><p style=\"text-align:center;\"><span><strong>សំណល់វេជ្ជសាស្រ្ត</strong></span></p><figure class=\"image image_resized\" style=\"width:78.29%;\"><img src=\"$url/storage/ckeditor-images/kisspng-medicine-nursing-drawing-doodle-medical-supplies-artwork-5aa1121385a852.2469974315205053635475.png\"></figure></td></tr><tr><td><p style=\"text-align:center;\"><span><strong>សំណល់កៅស៊ូ ឬស្បែក</strong></span></p><figure class=\"image image_resized\" style=\"width:82.23%;\"><img src=\"$url/storage/ckeditor-images/pngegg (13).png\"></figure></td><td>&nbsp;</td></tr></tbody></table></figure>",
                "sector_id": 1
            },
            {
                "question_en": "Reducing the Amount of Trash I Produce",
                "question_km": "កាត់បន្ថយការបង្កើតសំរាម​របស់ខ្ញុំ",
                "answer_en": "<p>By choosing re-usable items, we can prevent the amount of waste that goes to the landfill. Here are some examples:</p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><p style=\"text-align:center;\"><strong>Plastic</strong></p></td><td><p style=\"text-align:center;\"><strong>Substitute</strong></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:79.09%;\"><img src=\"$url/storage/ckeditor-images/KywsOjLC_pngkey.com-red-solo-cup-png-1464623.png\"></figure><p style=\"text-align:center;\"><span><strong>Plastic Cups</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:63.35%;\"><img src=\"$url/storage/ckeditor-images/bYgxlhXA_Tour Stemless Champange.png\"></figure><p style=\"text-align:center;\"><span><strong>Glass/clay Cups</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:65.96%;\"><img src=\"$url/storage/ckeditor-images/RC8ge7F7_32523_1000.png\"></figure><p style=\"text-align:center;\"><span><strong>Styrofoam Packaging</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:30.88%;\"><img src=\"$url/storage/ckeditor-images/K7RDoM9V_Chan srak 2.png\"></figure><p style=\"text-align:center;\"><span><strong>Food container / paper bags / Leaves</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:88.94%;\"><img src=\"$url/storage/ckeditor-images/YWOBSph1_Straws.H02.watermarked.2k.png\"></figure><p style=\"text-align:center;\"><span><strong>Plastic Straws</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:45.74%;\"><img src=\"$url/storage/ckeditor-images/4f5m9yFb_Fresh glass straw.png\"></figure><p style=\"text-align:center;\"><span><strong>Biodegradable straws</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:66.69%;\"><img src=\"$url/storage/ckeditor-images/Hg9QYVdz_Plastic bag.png\"></figure><p style=\"text-align:center;\"><span><strong>Plastic Bags</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:80.13%;\"><img src=\"$url/storage/ckeditor-images/KNwBSIaM_recycle bags.png\"></figure><p style=\"text-align:center;\"><span><strong>Paper or Cloth Bags</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:74.71%;\"><img src=\"$url/storage/ckeditor-images/232-2322857_see-the-waste-plastic-bottle.png\"></figure><p style=\"text-align:center;\"><span><strong>Plastic Bottles</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:72.1%;\"><img src=\"$url/storage/ckeditor-images/metal bottles.png\"></figure><p style=\"text-align:center;\"><strong>Metal Bottles</strong></p></td></tr></tbody></table></figure>",
                "answer_km": "<p>ដោយជ្រើសរើសសំភារៈដែលអាចប្រើប្រាស់ឡើងវិញ យើងអាចចូលរួមកាត់បន្ថយបរិមាណសំរាម ដែលត្រូវយកទៅចាក់ចោលនៅ​ទីលានចាក់សំរាម។ ខាងក្រោមនេះជាឧទាហរណ៍មួយចំនួន៖</p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><p style=\"text-align:center;\"><span><strong>សំភារៈប្លាស្ទិក</strong></span></p></td><td><p style=\"text-align:center;\"><span><strong>សំភារៈជំនួស</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:79.09%;\"><img src=\"$url/storage/ckeditor-images/KywsOjLC_pngkey.com-red-solo-cup-png-1464623.png\"></figure><p style=\"text-align:center;\"><span><strong>កែវប្លាស្ទិក</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:63.35%;\"><img src=\"$url/storage/ckeditor-images/bYgxlhXA_Tour Stemless Champange.png\"></figure><p style=\"text-align:center;\"><span><strong>កែវថ្ម ឬពែង</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:65.96%;\"><img src=\"$url/storage/ckeditor-images/RC8ge7F7_32523_1000.png\"></figure><p style=\"text-align:center;\"><span><strong>កញ្ចប់ស្នោរ</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:30.88%;\"><img src=\"$url/storage/ckeditor-images/K7RDoM9V_Chan srak 2.png\"></figure><p style=\"text-align:center;\"><span><strong>ចានស្រាក់ / កញ្ចប់ក្រដាស / ស្លឹកចេក ស្លឹកឈូក</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:88.94%;\"><img src=\"$url/storage/ckeditor-images/YWOBSph1_Straws.H02.watermarked.2k.png\"></figure><p style=\"text-align:center;\"><span><strong>បំពង់បឺតប្លាស្ទិក</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:45.74%;\"><img src=\"$url/storage/ckeditor-images/4f5m9yFb_Fresh glass straw.png\"></figure><p style=\"text-align:center;\"><span><strong>បំពង់បឺត ដែលងាយរលាយបាន</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:66.69%;\"><img src=\"$url/storage/ckeditor-images/Hg9QYVdz_Plastic bag.png\"></figure><p style=\"text-align:center;\"><span><strong>ថង់ប្លាស្ទិក</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:80.13%;\"><img src=\"$url/storage/ckeditor-images/KNwBSIaM_recycle bags.png\"></figure><p style=\"text-align:center;\"><span><strong>ថង់ក្រណាត់ ឬក្រដាស</strong></span></p></td></tr><tr><td><figure class=\"image image_resized\" style=\"width:74.71%;\"><img src=\"$url/storage/ckeditor-images/232-2322857_see-the-waste-plastic-bottle.png\"></figure><p style=\"text-align:center;\"><span><strong>ដបទឹកសុទ្ធ</strong></span></p></td><td><figure class=\"image image_resized\" style=\"width:72.1%;\"><img src=\"$url/storage/ckeditor-images/metal bottles.png\"></figure><p style=\"text-align:center;\"><span><strong>ដបទឹកធ្វើពីលោហៈ</strong></span></p></td></tr></tbody></table></figure>",
                "sector_id": 1
            },
            {
                "question_en": "Organic Waste",
                "question_km": "សំណល់សរីរាង្គ ឬសំណល់ជីវៈ",
                "answer_en": "<p>If they are not collected by the solid waste service provider, food scraps, coffee grounds, and small yard waste, like branches and leaves can often be composted at home or transformed into other products by companies.</p><p>Tips to make compost from &nbsp;household organic waste could be found in this video produced by KONRAD ADENAUER STIFTUNG &nbsp;EMBED: <a href=\"https://www.youtube.com/watch?v=a8m34JKbfh0&amp;feature=youtu.be\">https://www.youtube.com/watch?v=a8m34JKbfh0&amp;feature=youtu.be</a>.</p>",
                "answer_km": "<p>ប្រសិនបើ ក្រុមហ៊ុនប្រមូល និងដឹកជញ្ជូន​សំរាមមិន​​ប្រមូលសំរាម​របស់​យើង យើងក៏អាច​កែច្នៃ​សំណល់​សរីរាង្គមានដូចជា​ កំទេចកំទីអាហារ កាកកាហ្វេ និង សំណល់ផ្សេងៗនៅ​ក្នុងទីធ្លាផ្ទះ ដូចជាមែកឈើតូចៗ និង ស្លឹកឈើ ដោយយកមកធ្វើជាជីកំប៉ុសនៅតាម​ផ្ទះឬក៏អាចឱ្យ​ទៅ​ក្រុមហ៊ុនដែលកែច្នៃជាផលិតផលផ្សេងបាន។</p><p>វិធីណែនាំក្នុងការកែច្នៃជីកំប៉ុសពីសំណល់សរីរាង្គតាមផ្ទះ អាច​ទស្សនាបានតាមរយៈវីដេអូនេះដែលបានរៀបចំឡើងដោយ មូលនិធិខុនរ៉ាដ អាដិនណៅអ៊ែរ (KAS) / KONRAD ADENAUER STIFTUNG&nbsp;<br><a href=\"https://www.youtube.com/watch?v=a8m34JKbfh0&amp;feature=youtu.be\">https://www.youtube.com/watch?v=a8m34JKbfh0&amp;feature=youtu.be</a>.</p>",
                "sector_id": 1
            },
            {
                "question_en": "Recycling",
                "question_km": "ការកែច្នៃឡើងវិញ",
                "answer_en": "<p>Recycling varies based on type of waste, and it is limited in Cambodia.</p><p>For recyclable wastes, such as plastic bottles, metal cans and scraps, paper-cardboard and glass are advised to always store and sell to Et Chay (scavengers with pushing carts) or to junk shops, which citizens can earn some profits while saving the environment.</p>",
                "answer_km": "<p>ការកែច្នៃឡើងវិញប្រែប្រួលទៅ​តាមប្រភេទសំរាម ហើយ​ សកម្មភាពនេះនៅមានកម្រិតតិចតួចនៅប្រទេសកម្ពុជា។</p><p>សម្រាប់សំណល់​អាចកែច្នៃបាន មានដូចជា ដបប្លាស្ទិក កំប៉ុង និងកំទេចដែក ក្រដាស សំបកកេស និង កែវ ត្រូវតែបែងចែកស្តុកទុក និងលក់ទៅឱ្យ​អ្នកទិញអេតចាយ ឬដេប៉ូ​អេតចាយ ដែល​ធ្វើ​បែបនេះ​ ប្រជាពលរដ្ឋ​អាចទទួលបានប្រាក់​កំរៃខ្លះ ព្រមទាំង​ចូលរួមថែរក្សាបរិស្ថានផងដែរ។&nbsp;</p>",
                "sector_id": 1
            },
            {
                "question_en": "Waste Separation for Households",
                "question_km": "ការញែកសំណល់រឹងតាមផ្ទះ",
                "answer_en": "<p><span>Citizens shall implement waste separation at sources and well packaging of recyclable waste from disposable waste per instruction by the administration of municipalities, districts or Khans accordingly.&nbsp;</span></p><p><span>Not all areas have the ability to collect waste types separately, but at least citizens should be able to separate recyclable waste and hazardous waste from disposal waste. Remember that citizens can sell recyclable wastes or some e-waste as spare parts with good profit to informal collectors known as Et Chay (scavengers with pushing carts) or to junk shops which could be found easily in their neighborhood.&nbsp;</span></p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><span><strong>Type of Bin</strong></span></td><td><span><strong>Type of Waste</strong></span></td></tr><tr><td><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/Organic Waste.png\"></figure></td><td><span><strong>Organic Waste</strong>: Vegetable, fruit, rest of fish, grass, rest meat,&nbsp; rice and soup waste, tea leaves, coffee grounds, coconut shell, coconut husk,&nbsp;bagasse, leaves, small tree branch, etc.</span></td></tr><tr><td><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/Recyc_e Waste.png\"></figure></td><td><span><strong>Recyclable Waste</strong> can be processed and made into new materials, which means that these items may have some value. This includes: Aluminium cans, metals items, paper,card boards, plastic bottles, and other items that can be sold to informal collectors.</span></td></tr><tr><td><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/Disposal Waste.png\"></figure></td><td><span><strong>Other Waste</strong> is what we think of as <strong>TRASH</strong> and includes: Styrofoam packaging, old plastic bags, cloth scraps, shoes, leather, broken glass /bottle, diaper and other mixed waste.</span></td></tr></tbody></table></figure>",
                "answer_km": "<p>ប្រជាពលរដ្ឋត្រូវអនុវត្តការញែកសំណល់រឹង និងការវេចខ្ចប់សំរាមដែលអាចកែច្នៃឡើងវិញបាន ដាច់ដោយឡែកពីសំរាម ដែលត្រូវបោះចោលទៅតាមការណែនាំរបស់រដ្ឋបាល ក្រុង ស្រុក ឬខណ្ឌ។</p><p>មិនមែនគ្រប់តំបន់ទាំងអស់មានលទ្ធភាពក្នុងការប្រមូលសំរាមដាច់ដោយឡែក ទៅ​តាមប្រភេទសំរាម សំណល់រឹងផ្សេងៗនោះទេ ក៏ប៉ុន្តែយ៉ាងហោចណាស់ ប្រជាពលរដ្ឋ​គួរ​ញែកសំរាម​ ដែលអាចកែច្នៃឡើងវិញបាន និង សំណល់​គ្រោះថ្នាក់​ចេញពីសំរាមដែលត្រូវបោះចោល។ ត្រូវចាំថា ប្រជាពលរដ្ឋអាចទទួលបានកំរៃសមរម្យពី ការលក់សំណល់ដែលអាចកែច្នៃឡើងវិញបាន ឬ សំណល់​បរិក្ខារអគ្គិសនី និង​អេឡិចត្រូនិកខ្លះជាគ្រឿងបន្លាស់ ទៅឱ្យអ្នកប្រមូល​សំណល់​កែច្នៃក្រៅប្រព័ន្ធ ដែលត្រូវបានគេហៅថា អ្នកទិញអេតចាយ (ដោយមានអូសរទេះ ឬរម៉ក) ឫលក់ទៅឱ្យដេប៉ូអេតចាយ ដែលមាន​ និង​ងាយស្រួលរកក្នុងតំបន់ ដែល​ពួក​គាត់​រស់​នៅ។</p><figure class=\"table\"><table><colgroup><col style=\"width:50%;\"><col style=\"width:50%;\"></colgroup><tbody><tr><td><span><strong>ប្រភេទធុងសំរាម</strong></span></td><td><span><strong>ប្រភេទសំរាម</strong></span></td></tr><tr><td><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/Organic Waste.png\"></figure></td><td><strong>សំណល់សរីរាង្គឬសំណល់​ជីវៈ</strong> មានដូចជា បន្លែ ផ្លែឈើ កាកសំណល់ត្រី សាច់ បាយ សម្ល តែ កាកកាហ្វេ សំបកដូង ស្រកីដូង កាកអំពៅ ស្លឹកឈើ មែកឈើតូចៗ និងស្មៅ​ជាដើម។&nbsp;</td></tr><tr><td><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/Recyc_e Waste.png\"></figure></td><td><span><strong>សំណល់អាចកែច្នៃបាន​ </strong>ជាសំណល់​ដែលអាចបំលែង​ឱ្យ​​ទៅជាវត្ថុធាតុដើម​ថ្មី នេះ​បានន័យថា សំណល់​ទាំងនេះនៅមានតម្លៃនៅឡើយ រួមមានដូចជា កំប៉ុងអាលុយមីញ៉ូម សំភារៈដែលធ្វើពីដែក ក្រដាស សំបកកេស&nbsp; ដបប្លាស្ទិក និង សំភារៈផ្សេងទៀត ដែលអាចលក់ទៅឱ្យអ្នកទិញអេតចាយ ឬដេប៉ូអេតចាយ។</span></td></tr><tr><td><figure class=\"image\"><img src=\"$url/storage/ckeditor-images/Disposal Waste.png\"></figure></td><td><strong>សំណល់ផ្សេងៗ</strong> គឺជាអ្វីក៏ដោយដែលអ្នកគិតថាជាសំរាម រួមមានដូចជា៖ កញ្ចប់ស្នោរ ថង់ប្លាស្ទិកចាស់ៗ កំទេចក្រណាត់ ស្បែកជើង សំភារៈធ្វើពីស្បែក កែវ ឬអំបែងដប កន្ទបទារក និង​សំណល់ផ្សេងទៀត។</td></tr></tbody></table></figure><p><br>&nbsp;</p>",
                "sector_id": 1
            },
            {
                "question_en": "How to Store Trash",
                "question_km": "របៀបនៃការវេចខ្ចប់​ និងទុកដាក់សំរាម",
                "answer_en": "<ul><li><span>Liquid wastes and water should be removed and not dripping or leaking</span></li><li><span>The smell should be contained.&nbsp;</span></li><li><span>Store inside appropriate bins or waste containers - if possible inside the house or behind a fence until the scheduled day for trash collection.</span></li></ul>",
                "answer_km": "<ul><li><span>ត្រូវចាក់ចោលសំណល់រាវ និងទឹក កុំឱ្យមានការលេចធ្លាយ ឬជ្រាបទឹកចេញ។</span></li><li><span>កុំឱ្យមានភាយក្លិនស្អុយ។</span></li><li><span>រក្សាទុកក្នុងធុងសំរាមឱ្យបានត្រឹមត្រូវ ប្រសិនបើអាច ត្រូវទុកក្នងបរិវេណលំនៅដ្ឋាន ឬ ក្នុងរបង និងបញ្ចេញចោលទៅតាមកាលវិភាគប្រមូលសំរាមដែលបានកំណត់។</span></li></ul>",
                "sector_id": 1
            },
            {
                "question_en": "My Role in Trash Collection",
                "question_km": "តួនាទីរបស់ខ្ញុំនៅក្នុងការប្រមូលសំរាម",
                "answer_en": "<p>Citizens have to:</p><ul><li>Dispose of trash in proper bags or&nbsp; private bins&nbsp; that contain the smell and prevent leaking.</li><li>Set them out at the instructed place and time according to the administration of municipalities, districts or Khans.</li><li>Pay for waste services that are including waste collection, transportation and disposal at landfills.</li><li>Do not dispose or burn municipal solid waste along the roads, public fields, in sewage systems or public water sources or on privately-owned land.&nbsp;&nbsp;</li><li>If&nbsp; trash, recyclables and organic wastes are collected separately, the household should store them in separate containers and set them out accordingly.</li></ul>",
                "answer_km": "<p>ប្រជាពលរដ្ឋត្រូវ៖</p><ul><li>វេចខ្ចប់សំរាមដាក់ក្នុងថង់ ឬធុងសំរាមផ្ទាល់ខ្លួនមិនឱ្យ​មាន​ភាយ​ក្លិន​ស្អុយ​ ឬ​លេច​ជ្រាប​ទឹកស្អុយ។</li><li>បញ្ចេញសំរាមតាមទីតាំង និងម៉ោងដែលកំណត់ដោយរដ្ឋបាល ក្រុង ស្រុក ឬខណ្ឌ។</li><li>បង់ថ្លៃសេវា ប្រមូល ដឹកជញ្ជូន និងសេវាទីលានទុកដាក់សំរាម។</li><li>មិនត្រូវបោះចោល ឬដុតសំរាម សំណល់រឹងទីប្រជុំជន នៅតាមដងផ្លូវ ទីសាធារណៈ ទីវាល ប្រព័ន្ធទឹកលូ ឬប្រភពទឹកសាធារណៈ ឬក្នុងដីកម្មសិទ្ធិឯកជន។</li><li>ប្រសិនបើ សំរាម គឺជាសំណល់ដែលអាចកែច្នៃឡើងវិញបាន និងជាសំណល់សរីរាង្គ ដែលអាចប្រមូលបានដាច់ដោយឡែក តាមផ្ទះគួរញែកដាក់ក្នុងធុងផ្សេង និង បញ្ចេញចោលនៅពេលដែលសមស្រប។</li></ul>",
                "sector_id": 1
            }
        ]
        JSON;

        $data = json_decode($json_data, true);
        foreach ($data as $faq) {
            Faq::query()
                ->create($faq);
        }
    }
}
